spring:
  application:
    name: reporter
  web:
    locale: en_US
  webflux:
    base-path: /reporter
  profiles:
    active: reporter
  datasource:
    host: ${database-host:localhost}
    port: ${database-port:1433}
    database: ${database-name:dummyName}
    username: ${database-user:dummyUser}
    password: ${database-password:dummyPassword}
  flyway:
    url: ${flyway-url:localhost}
    user: ${database-user:dummyUser}
    password: ${database-password:dummyPassword}
    enabled: true
server:
  port: 7500